### PR TITLE
fix numbering toggle

### LINKED ISSUE #1: "Show numbers" toggle uses wrong numbering scheme
Given the following DSL:

```
place Foo
	My Affordance
	> A Nested Affordance
```

This renders as:

```
1. Foo
	1.1 My Affordance
		1.1.1 A Nested Affordance
```

But when `Show Numbers` is toggled off, and then back on again, it renders as:

```
1. Foo
	1.1 My Affordance
		1.2 A Nested Affordance
```

Where `1.2` should actually be `1.1.1`.

### PR DESCRIPTION
**Pull request by JeanMertz**
This fixes an issue with the numbering toggle incorrectly iterating over all affordances of a place, and applying the wrong level-based index to them.

closes #1.

### CODE REVIEW

File: crates/butter/src/plugins/canvas/affordance.rs [hunk 1]
```diff
@@ -332,22 +332,43 @@ fn toggle_numbering(
...
+
+            for lvl in 0..=level {
+                let index: usize = indices.get(&lvl).copied().unwrap_or_default() + 1;
+                let index = if lvl == level {
+                    index
+                } else {
+                    index.saturating_sub(1)
+                };
+
+                numbers.push_str(&format!("{}.", index))
```
Comment (parasyte) [inline crates/butter/src/plugins/canvas/affordance.rs:365]: I'm not sure if this is worth considering, but any time I see this pattern where a `String` is immediately borrowed and dropped, it makes me think that `write!(&mut numbers, ...)` would be preferred. There's even a clippy lint for this: https://rust-lang.github.io/rust-clippy/stable/index.html#/format_push_string

**Review by parasyte — APPROVED** [review]
LGTM.

**Comment by danpape** [comment]
I think I get what is happening--looks good.

**Review by danpape — APPROVED** [review]
Looks good.

File: crates/butter/src/plugins/canvas/affordance.rs (hunk 1 above)
Comment (JeanMertz) [reply crates/butter/src/plugins/canvas/affordance.rs:365]: Good catch! I'll make the change.
